server:
  port: 8080

spring:
  application:
    name: iot
  
  datasource:
    url: jdbc:mysql://localhost:3306/iot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Thanhmessi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

mqtt:
  url: tcp://localhost:1884
  client-id: spring-boot-backend
